apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:xXdS+tsrVF2ROaKDyQx5ZORjVBnc3z3yCXEPrllCr1ZqAEupqEatKuaMEAUWsLD22aZz9XOGfGZqzp3p6cOPHL+kYFU9uhbeObKLyWGtHKp2UbGBPVsKOQWEsvU1aQ==,iv:b8pVCPDlwJNtaHBXWJup3Cg6KdjkO0mim1GGK8AW86E=,tag:Y2M3+sHH5FawmuI/a51uKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16pm6ewm58ghgf5qqxzzql4txqf50pk9ez9gwn5eetup37lmd0c8sushtrx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArK1crVlJRT1pYanpIT2pT
            OU01SmtJRThibURHTnFoQkZPdW85VVB4YlYwCm1vTU1nTVd5NEVPS0k1bVltYnVC
            Z1VMY3NJSDdYUVk2MEI3MExmblcvSHcKLS0tIEZIN1A1eEtnWWFOaUdLbnZiZEd5
            eWl0VTFSRCsyZVdyeFpXUHFsbmhOcG8K0ICogF6EjXCtJ+pfCnwB2EvUQXynZ2c5
            1XBW+zhYRTvX9nsdFSCTxWNn8rpgWxlu64qTMqcjMoZP9tYyO/at5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-16T11:11:19Z"
    mac: ENC[AES256_GCM,data:LwP5qQ1+dVAMtW/37YLA5Wzw4MZyzM1Wmbbemx+yUzY53ySaSio+lMFJrXPMXm0HkZnTFucA8ueeCs7QMAmQxPGS4yx93zC3bB3HmGUUJYAC297rsFTGO0qudANOQkhKvmZ5ALbSg/ISPpQBKQjlVU4AqGFLypW+GUfZsBGvTXg=,iv:Wl7+Jk2yAcD986xCB8X0JZ+LijYaj9auRanx/eB9zAY=,tag:b6ZzbzMho5f8JJ2FFRHXQQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
