apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:tyNKJCYy8dSQIIQAUxS8JNUUMuZY2t6vk1Y4FvYZDCRw60ESd1ESj+SCYxTR7knQ9BpzD0fqcx8yfLeJvIonmfsgut1RhhtUIWFNz35o7dwaKQufhoFRCnJHsVoBUw==,iv:+oYpd40icQ8GbBfvgV474FxxFQOkG/v6jQue4QOrmpA=,tag:5BIPxndusET4NjHKjKXnsg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16pm6ewm58ghgf5qqxzzql4txqf50pk9ez9gwn5eetup37lmd0c8sushtrx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjd1k0Qy9VajlkMmc4Wm02
            VVFXRVNOWndKaUxDVjEzRTNsUnV6YWZqMzI0CmZrS09Xa1F5ZE5vQURpRFR1Z0Fs
            NXREU0dqZHpxdUt5S25yOUc5R3hRL0UKLS0tIGU4TmY4Q3V1b1JtNHRCVExkMmdP
            R04yZUc5Vjkza2VWYkpSU2F3UFViTFUKeOMgtLrL5IKoZM1E/8PnEOVFpi94GT1i
            4BOHjUajRCMqM+RV9Osj6j0DGLaOkSg9Rv78AEVadvHhQ6cYXGTwrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-15T22:02:18Z"
    mac: ENC[AES256_GCM,data:nSknYu6qiagcqhgAdDNkxjYCzjZCE/LA/K7pgpqL+X/wqnvRQLJYZnucn/oyBFDv1Mqb3Mrvr6GBFpY4QthhtA7aDTdBjM5pblMwdm14AqGHPYeOuRsRgps7CG3nM98XPfZNVflSA8U+4wLm8mTmnnXGGQGdcwORPu+0SfUfRIg=,iv:l5EUpOyeCDsfBJcldv14owo8Q+CtMK2taEtGcl99cR8=,tag:xvYQqxrJ4Y99RZlF/yEhOQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
