apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:UMNrb7UpTj+KqDzrx9I4K0gqSZHlI7933e2ucYrecbes9x0QU3KIXMMvjUM5vxkw3Ncs0AUYGYYUInOFoQNaAaccGVzJ6ZkwPiduG7MdNUX/lAqHTq7BwjFhxDlijA==,iv:/k59Z10VVKNids3Qp61C8vkk7QJUEhIa1FdnEScCXB8=,tag:7qSEHJl+MS6Gt9E27AKXsQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16pm6ewm58ghgf5qqxzzql4txqf50pk9ez9gwn5eetup37lmd0c8sushtrx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwRm1MVDdRVWFaQllHVm9k
            Rm80OFlNeURLMVoxL2dsTjVZcVFBMHFIZm04CmJ0eUJYSThKWWl2eWxObDJycThJ
            bWVwNEdaKy9kZXJhWEtiME1BeUl5VEUKLS0tIFJ5Y3JNUzRWRXBLOXNmay9ucmM0
            NDRPd240NWhzbTlYV2xJTExVSExuR2MKVwSykuAi3bQUdmoHzRrHYL6QfOmw3W2o
            RgbBG+nMERzxzJAviUJvSm1zPEde4pLVCB9jsC7SUTCmczyaj+tvLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-10T20:20:22Z"
    mac: ENC[AES256_GCM,data:QKTfOio4xO6YEwhkvqqpOybfv7pFRlrRB+W8zx9FqvU+o3OqZJKgy1g8cSX9KSYEqZCUOmg1Ft9Rzjsr/OZbplO2Uh80M06h63IdAPZGIYxfRulwYPqTSFFbNBBy/u6QqQnIadARRDDtLIrM3JOlu/iZYEzSkVGfgOEvwKk1olM=,iv:epCGibmI6ToDxLYitbxM0X5Zt4XTksGOPczxl6IOV6E=,tag:S3C5L8ocfZrqWDgWkg8oPA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
