apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:LsaMr+Ycf17byEA/Yrnz8Wy7UC3nUiHphOeRpye0zVI=,iv:9N/7syj0ZeJJtNGyaU+XSQrt55JBBYQG5fiCK0PxoRE=,tag:TJfLonwGp+9mI+L7GU053g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16pm6ewm58ghgf5qqxzzql4txqf50pk9ez9gwn5eetup37lmd0c8sushtrx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTFRIZjM2Wnlnd2JGYldU
            N0FuNzdiRWU2dGtYZ3JrY2FlTjNSN1FENlJ3Cmcyd0NzN25LdGFrZDV0NlYwYzRU
            L0N3VE1mUXJDODFWaXFzUmJwUU12MFkKLS0tIEJPOEJvdUZnSHBGdWV0NmI3Zitx
            NEg4RHY2dlA5M3pkNmhEZ01UQzEzMEkKjYdK8EjhemlSjFxWbb93nrNedxXipyZf
            6MdKFSvD0wTka24xugimH2Jzwx7UuM2fANUfajFDkZxkIFYQOfq0Iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-15T17:14:50Z"
    mac: ENC[AES256_GCM,data:acHyl2CPwYiTdXam86OgulEb9H3uHtjioGGm37OtRk5gNmLigbyBsmNLl6ZJTzzqCodwwEKuZA0xk8YawervS0GtmBVLfSdLeh2OzsCoQVu1uM4Uy0nJALimYlSdqY7TPyEVDQEOO5HQIcu0jMKyqHMFxPaoiVD0orMoUiPwReA=,iv:b3dH37DBiQ59RzU/3T1BQPYA68abA//zwglAO7sRvMs=,tag:5VeezKO98moOmht5qseIyA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
