apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:m8yqaZdATI4nShc03RlNA2pkTEa5k+6simDYiRMFKXE=,iv:GnalOOl5bgOq5EU9JENoRe8bflff5SCnXxLe9ovQ3T4=,tag:ySr5UcFimjf5o85+2Kx6lw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16pm6ewm58ghgf5qqxzzql4txqf50pk9ez9gwn5eetup37lmd0c8sushtrx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSzd6OVdITEVQenN1YUsr
            NTh6OU1keUt1SU9Vb1YyYnE3d1BpZFNnK1ZNCkl1aVZLMVQrTkpWQzF4VW5QU25S
            WS94T2hFQVplU25xZEFVWjBqd2VWVG8KLS0tIGxpbmRJUVlZV2hlZTNMUWMrRkJ1
            Wi9RUFZJeW1NR0Z0V3l2ZCtoVnBqTzQKJ0mTgZ+Otj8hyfrWhWl3xIanXuGn3qFM
            vter52gnNP6f+B8R3WKteaoe8706dKqRcxDS2tQVdi/irEHk7un/hQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-11T19:29:50Z"
    mac: ENC[AES256_GCM,data:zSXLHF3O2EKFI3g/n3kRlClG1IPPxcwrQoRh/PH8DPgvJ2UEWx5PpAlgKCpXEb9MfhSZrWudTo+r2zcdp9Xnv6BDmaT2ssVY6yudMevfpauNJ3W9Zk9Ox8Iw62S7M2k6W2wXOR7b4Ro7E0yLegMW/0FVISJdye+5A+t0wVwvqYY=,iv:KNUN5mVkTvRHkmAt6g7fG4MOUuCBAz+U9prCKCeWtk8=,tag:pAEoZI4n457RMxJiNLWcAg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
